const codes = {
	"1-3-3-2-2": /^(\d{0,1})(\d{0,3})(\d{0,3})(\d{0,2})(\d{0,2}).*/,
	"1-3-3-4": /^(\d{0,1})(\d{0,3})(\d{0,3})(\d{0,4}).*/,
	"2-1-3-4": /^(\d{0,2})(\d{0,1})(\d{0,3})(\d{0,4}).*/,
	"2-1-4-4": /^(\d{0,2})(\d{0,1})(\d{0,4})(\d{0,4}).*/,
	"2-2-2-2-2": /^(\d{0,2})(\d{0,2})(\d{0,2})(\d{0,2})(\d{0,2}).*/,
	"2-2-3-2-2": /^(\d{0,2})(\d{0,2})(\d{0,3})(\d{0,2})(\d{0,2}).*/,
	"2-2-3-3": /^(\d{0,2})(\d{0,2})(\d{0,3})(\d{0,3}).*/,
	"2-2-3-4": /^(\d{0,2})(\d{0,2})(\d{0,3})(\d{0,4}).*/,
	"2-2-4-4": /^(\d{0,2})(\d{0,2})(\d{0,4})(\d{0,4}).*/,
	"2-3-2-3": /^(\d{0,2})(\d{0,3})(\d{0,2})(\d{0,3}).*/,
	"2-3-3-3": /^(\d{0,2})(\d{0,3})(\d{0,3})(\d{0,3}).*/,
	"2-3-3-4": /^(\d{0,2})(\d{0,3})(\d{0,3})(\d{0,4}).*/,
	"2-3-4-3": /^(\d{0,2})(\d{0,3})(\d{0,4})(\d{0,3}).*/,
	"2-3-4-4": /^(\d{0,2})(\d{0,3})(\d{0,4})(\d{0,4}).*/,
	"2-4-3-3": /^(\d{0,2})(\d{0,4})(\d{0,3})(\d{0,3}).*/,
	"2-4-4": /^(\d{0,2})(\d{0,4})(\d{0,4}).*/,
	"3-1-2-2-2": /^(\d{0,3})(\d{0,1})(\d{0,2})(\d{0,2})(\d{0,2}).*/,
	"3-1-3-2-2": /^(\d{0,3})(\d{0,1})(\d{0,3})(\d{0,2})(\d{0,2}).*/,
	"3-1-3-3": /^(\d{0,3})(\d{0,1})(\d{0,3})(\d{0,3}).*/,
	"3-1-3-4": /^(\d{0,3})(\d{0,1})(\d{0,3})(\d{0,4}).*/,
	"3-1-4-4": /^(\d{0,3})(\d{0,1})(\d{0,4})(\d{0,4}).*/,
	"3-1-6": /^(\d{0,3})(\d{0,1})(\d{0,6}).*/,
	"3-2-2-2": /^(\d{0,3})(\d{0,2})(\d{0,2})(\d{0,2}).*/,
	"3-2-2-2-2": /^(\d{0,3})(\d{0,2})(\d{0,2})(\d{0,2})(\d{0,2}).*/,
	"3-2-2-4": /^(\d{0,3})(\d{0,2})(\d{0,2})(\d{0,4}).*/,
	"3-2-2-5": /^(\d{0,3})(\d{0,2})(\d{0,2})(\d{0,5}).*/,
	"3-2-3": /^(\d{0,3})(\d{0,2})(\d{0,3}).*/,
	"3-2-3-2-2": /^(\d{0,3})(\d{0,2})(\d{0,3})(\d{0,2})(\d{0,2}).*/,
	"3-2-3-3": /^(\d{0,3})(\d{0,2})(\d{0,3})(\d{0,3}).*/,
	"3-2-3-4": /^(\d{0,3})(\d{0,2})(\d{0,3})(\d{0,4}).*/,
	"3-2-4": /^(\d{0,3})(\d{0,2})(\d{0,4}).*/,
	"3-2-4-3": /^(\d{0,3})(\d{0,2})(\d{0,4})(\d{0,3}).*/,
	"3-2-5": /^(\d{0,3})(\d{0,2})(\d{0,5}).*/,
	"3-2-6": /^(\d{0,3})(\d{0,2})(\d{0,6}).*/,
	"3-3-2-2": /^(\d{0,3})(\d{0,3})(\d{0,2})(\d{0,2}).*/,
	"3-3-2-2-2": /^(\d{0,3})(\d{0,3})(\d{0,2})(\d{0,2})(\d{0,2}).*/,
	"3-3-2-3": /^(\d{0,3})(\d{0,3})(\d{0,2})(\d{0,3}).*/,
	"3-3-3": /^(\d{0,3})(\d{0,3})(\d{0,3}).*/,
	"3-3-3-2-2": /^(\d{0,3})(\d{0,3})(\d{0,3})(\d{0,2})(\d{0,2}).*/,
	"3-3-3-3": /^(\d{0,3})(\d{0,3})(\d{0,3})(\d{0,3}).*/,
	"3-3-3-4": /^(\d{0,3})(\d{0,3})(\d{0,3})(\d{0,4}).*/,
	"3-3-4": /^(\d{0,3})(\d{0,3})(\d{0,4}).*/,
	"3-3-5": /^(\d{0,3})(\d{0,3})(\d{0,5}).*/,
	"3-3-6": /^(\d{0,3})(\d{0,3})(\d{0,6}).*/,
	"3-4": /^(\d{0,3})(\d{0,4}).*/,
	"3-4-4": /^(\d{0,3})(\d{0,4})(\d{0,4}).*/,
	"3-4-6": /^(\d{0,3})(\d{0,4})(\d{0,6}).*/,
	"3-5": /^(\d{0,3})(\d{0,5}).*/,
	"3-5-4": /^(\d{0,3})(\d{0,5})(\d{0,4}).*/,
	"3-6": /^(\d{0,3})(\d{0,6}).*/,
};

export const countries = [
	{ name: "Afghanistan", dial_code: "+93", code: "AF", mask: codes["2-2-3-4"] },
	{ name: "Aland Islands", dial_code: "+358", code: "AX", mask: codes["3-3-3-2-2"] },
	{ name: "Albania", dial_code: "+355", code: "AL", mask: codes["3-3-3-3"] },
	{ name: "Algeria", dial_code: "+213", code: "DZ", mask: codes["3-2-3-4"] },
	{ name: "AmericanSamoa", dial_code: "+1684", code: "AS", mask: codes["1-3-3-4"] },
	{ name: "Andorra", dial_code: "+376", code: "AD", mask: codes["3-3-3"] },
	{ name: "Angola", dial_code: "+244", code: "AO", mask: codes["3-3-3-3"] },
	{ name: "Anguilla", dial_code: "+1264", code: "AI", mask: codes["1-3-3-4"] },
	{ name: "Antigua and Barbuda", dial_code: "+1268", code: "AG", mask: codes["1-3-3-4"] },
	{ name: "Argentina", dial_code: "+54", code: "AR", mask: codes["2-3-3-4"] },
	{ name: "Armenia", dial_code: "+374", code: "AM", mask: codes["3-2-3-3"] },
	{ name: "Aruba", dial_code: "+297", code: "AW", mask: codes["3-3-4"] },
	{ name: "Australia", dial_code: "+61", code: "AU", mask: codes["2-1-4-4"] },
	{ name: "Austria", dial_code: "+43", code: "AT", mask: codes["2-3-3-4"] },
	{ name: "Azerbaijan", dial_code: "+994", code: "AZ", mask: codes["3-2-3-2-2"] },
	{ name: "Bahamas", dial_code: "+1242", code: "BS", mask: codes["1-3-3-4"] },
	{ name: "Bahrain", dial_code: "+973", code: "BH", mask: codes["3-4-4"] },
	{ name: "Bangladesh", dial_code: "+880", code: "BD", mask: codes["3-2-3-3"] },
	{ name: "Barbados", dial_code: "+1246", code: "BB", mask: codes["1-3-3-4"] },
	{ name: "Belarus", dial_code: "+375", code: "BY", mask: codes["3-2-3-2-2"] },
	{ name: "Belgium", dial_code: "+32", code: "BE", mask: codes["1-3-3-4"] },
	{ name: "Belize", dial_code: "+501", code: "BZ", mask: codes["3-3-4"] },
	{ name: "Benin", dial_code: "+229", code: "BJ", mask: codes["3-2-2-4"] },
	{ name: "Bermuda", dial_code: "+1441", code: "BM", mask: codes["1-3-3-4"] },
	{ name: "Bhutan", dial_code: "+975", code: "BT", mask: codes["3-2-3-3"] },
	{ name: "Bolivia, Plurinational State of", dial_code: "+591", code: "BO", mask: codes["3-1-3-4"] },
	{ name: "Bosnia and Herzegovina", dial_code: "+387", code: "BA", mask: codes["3-2-4"] },
	{ name: "Botswana", dial_code: "+267", code: "BW", mask: codes["3-2-3-3"] },
	{ name: "Brazil", dial_code: "+55", code: "BR", mask: codes["2-2-4-4"] },
	{ name: "British Indian Ocean Territory", dial_code: "+246", code: "IO", mask: codes["3-3-4"] },
	{ name: "Brunei Darussalam", dial_code: "+673", code: "BN", mask: codes["3-3-4"] },
	{ name: "Bulgaria", dial_code: "+359", code: "BG", mask: codes["3-3-3-3"] },
	{ name: "Burkina Faso", dial_code: "+226", code: "BF", mask: codes["3-2-2-4"] },
	{ name: "Burundi", dial_code: "+257", code: "BI", mask: codes["3-2-2-4"] },
	{ name: "Cambodia", dial_code: "+855", code: "KH", mask: codes["3-2-3-3"] },
	{ name: "Cameroon", dial_code: "+237", code: "CM", mask: codes["3-4-4"] },
	{ name: "Canada", dial_code: "+1", code: "CA", mask: codes["1-3-3-4"] },
	{ name: "Cape Verde", dial_code: "+238", code: "CV", mask: codes["3-3-2-2"] },
	{ name: "Cayman Islands", dial_code: "+ 345", code: "KY", mask: codes["1-3-3-4"] },
	{ name: "Central African Republic", dial_code: "+236", code: "CF", mask: codes["3-2-2-4"] },
	{ name: "Chad", dial_code: "+235", code: "TD", mask: codes["3-2-2-2-2"] },
	{ name: "Chile", dial_code: "+56", code: "CL", mask: codes["2-1-4-4"] },
	{ name: "China", dial_code: "+86", code: "CN", mask: codes["2-3-4-4"] },
	{ name: "Christmas Island", dial_code: "+61", code: "CX", mask: codes["2-1-4-4"] },
	{ name: "Cocos (Keeling) Islands", dial_code: "+61", code: "CC", mask: codes["2-1-4-4"] },
	{ name: "Colombia", dial_code: "+57", code: "CO", mask: codes["2-3-3-4"] },
	{ name: "Comoros", dial_code: "+269", code: "KM", mask: codes["3-2-4"] },
	{ name: "Congo", dial_code: "+242", code: "CG", mask: codes["3-2-3-4"] },
	{ name: "Congo, The Democratic Republic of the Congo", dial_code: "+243", code: "CD", mask: codes["3-3-3-3"] },
	{ name: "Cook Islands", dial_code: "+682", code: "CK", mask: codes["3-2-3"] },
	{ name: "Costa Rica", dial_code: "+506", code: "CR", mask: codes["3-4-4"] },
	{ name: "Cote d'Ivoire", dial_code: "+225", code: "CI", mask: codes["3-2-3-3"] },
	{ name: "Croatia", dial_code: "+385", code: "HR", mask: codes["3-2-3-3"] },
	{ name: "Cuba", dial_code: "+53", code: "CU", mask: codes["2-1-3-4"] },
	{ name: "Cyprus", dial_code: "+357", code: "CY", mask: codes["3-2-3-3"] },
	{ name: "Czech Republic", dial_code: "+420", code: "CZ", mask: codes["3-3-3-3"] },
	{ name: "Denmark", dial_code: "+45", code: "DK", mask: codes["2-2-2-2-2"] },
	{ name: "Djibouti", dial_code: "+253", code: "DJ", mask: codes["3-2-2-2-2"] },
	{ name: "Dominica", dial_code: "+1767", code: "DM", mask: codes["1-3-3-4"] },
	{ name: "Dominican Republic", dial_code: "+1849", code: "DO", mask: codes["1-3-3-4"] },
	{ name: "Ecuador", dial_code: "+593", code: "EC", mask: codes["3-2-3-4"] },
	{ name: "Egypt", dial_code: "+20", code: "EG", mask: codes["2-3-3-4"] },
	{ name: "El Salvador", dial_code: "+503", code: "SV", mask: codes["3-2-2-4"] },
	{ name: "Equatorial Guinea", dial_code: "+240", code: "GQ", mask: codes["3-2-3-4"] },
	{ name: "Eritrea", dial_code: "+291", code: "ER", mask: codes["3-1-3-3"] },
	{ name: "Estonia", dial_code: "+372", code: "EE", mask: codes["3-4-4"] },
	{ name: "Ethiopia", dial_code: "+251", code: "ET", mask: codes["3-2-3-4"] },
	{ name: "Falkland Islands (Malvinas)", dial_code: "+500", code: "FK", mask: codes["3-5"] },
	{ name: "Faroe Islands", dial_code: "+298", code: "FO", mask: codes["3-3-3"] },
	{ name: "Fiji", dial_code: "+679", code: "FJ", mask: codes["3-2-5"] },
	{ name: "Finland", dial_code: "+358", code: "FI", mask: codes["3-3-3-2-2"] },
	{ name: "France", dial_code: "+33", code: "FR", mask: codes["2-3-3-3"] },
	{ name: "French Guiana", dial_code: "+594", code: "GF", mask: codes["3-5-4"] },
	{ name: "French Polynesia", dial_code: "+689", code: "PF", mask: codes["3-2-2-2"] },
	{ name: "Gabon", dial_code: "+241", code: "GA", mask: codes["3-1-2-2-2"] },
	{ name: "Gambia", dial_code: "+220", code: "GM", mask: codes["3-3-2-2"] },
	{ name: "Georgia", dial_code: "+995", code: "GE", mask: codes["3-3-3-3"] },
	{ name: "Germany", dial_code: "+49", code: "DE", mask: codes["2-3-3-4"] },
	{ name: "Ghana", dial_code: "+233", code: "GH", mask: codes["3-3-3-3"] },
	{ name: "Gibraltar", dial_code: "+350", code: "GI", mask: codes["3-3-5"] },
	{ name: "Greece", dial_code: "+30", code: "GR", mask: codes["2-3-3-4"] },
	{ name: "Greenland", dial_code: "+299", code: "GL", mask: codes["3-2-2-2"] },
	{ name: "Grenada", dial_code: "+1473", code: "GD", mask: codes["1-3-3-4"] },
	{ name: "Guadeloupe", dial_code: "+590", code: "GP", mask: codes["3-3-3-3"] },
	{ name: "Guam", dial_code: "+1671", code: "GU", mask: codes["1-3-3-4"] },
	{ name: "Guatemala", dial_code: "+502", code: "GT", mask: codes["3-1-3-4"] },
	{ name: "Guernsey", dial_code: "+44", code: "GG", mask: codes["2-2-4-4"] },
	{ name: "Guinea", dial_code: "+224", code: "GN", mask: codes["3-2-3-3"] },
	{ name: "Guinea-Bissau", dial_code: "+245", code: "GW", mask: codes["3-1-6"] },
	{ name: "Guyana", dial_code: "+595", code: "GY", mask: codes["3-3-4"] },
	{ name: "Haiti", dial_code: "+509", code: "HT", mask: codes["3-2-2-4"] },
	{ name: "Holy See (Vatican City State)", dial_code: "+379", code: "VA", mask: codes["3-3-4"] },
	{ name: "Honduras", dial_code: "+504", code: "HN", mask: codes["3-4-4"] },
	{ name: "Hong Kong", dial_code: "+852", code: "HK", mask: codes["3-4-4"] },
	{ name: "Hungary", dial_code: "+36", code: "HU", mask: codes["2-3-3-3"] },
	{ name: "Iceland", dial_code: "+354", code: "IS", mask: codes["3-3-4"] },
	{ name: "India", dial_code: "+91", code: "IN", mask: codes["2-4-3-3"] },
	{ name: "Indonesia", dial_code: "+62", code: "ID", mask: codes["2-3-3-4"] },
	{ name: "Iran, Islamic Republic of Persian Gulf", dial_code: "+98", code: "IR", mask: codes["2-3-3-4"] },
	{ name: "Iraq", dial_code: "+964", code: "IQ", mask: codes["3-3-3-4"] },
	{ name: "Ireland", dial_code: "+353", code: "IE", mask: codes["3-3-3-3"] },
	{ name: "Isle of Man", dial_code: "+44", code: "IM", mask: codes["2-2-4-4"] },
	{ name: "Israel", dial_code: "+972", code: "IL", mask: codes["3-2-3-4"] },
	{ name: "Italy", dial_code: "+39", code: "IT", mask: codes["2-3-4-3"] },
	{ name: "Jamaica", dial_code: "+1876", code: "JM", mask: codes["1-3-3-4"] },
	{ name: "Japan", dial_code: "+81", code: "JP", mask: codes["2-3-4-4"] },
	{ name: "Jersey", dial_code: "+44", code: "JE", mask: codes["2-2-4-4"] },
	{ name: "Jordan", dial_code: "+962", code: "JO", mask: codes["3-1-4-4"] },
	{ name: "Kazakhstan", dial_code: "+77", code: "KZ", mask: codes["2-2-3-2-2"] },
	{ name: "Kenya", dial_code: "+254", code: "KE", mask: codes["3-3-6"] },
	{ name: "Kiribati", dial_code: "+686", code: "KI", mask: codes["3-2-3"] },
	{ name: "Korea, Democratic People's Republic of Korea", dial_code: "+850", code: "KP", mask: codes["3-3-3-4"] },
	{ name: "Korea, Republic of South Korea", dial_code: "+82", code: "KR", mask: codes["2-2-3-4"] },
	{ name: "Kuwait", dial_code: "+965", code: "KW", mask: codes["3-4-4"] },
	{ name: "Kyrgyzstan", dial_code: "+996", code: "KG", mask: codes["3-3-3-3"] },
	{ name: "Laos", dial_code: "+856", code: "LA", mask: codes["3-2-3-3"] },
	{ name: "Latvia", dial_code: "+371", code: "LV", mask: codes["3-2-3-3"] },
	{ name: "Lebanon", dial_code: "+961", code: "LB", mask: codes["3-2-3-3"] },
	{ name: "Lesotho", dial_code: "+266", code: "LS", mask: codes["3-1-3-4"] },
	{ name: "Liberia", dial_code: "+231", code: "LR", mask: codes["3-2-3-3"] },
	{ name: "Libyan Arab Jamahiriya", dial_code: "+218", code: "LY", mask: codes["3-2-3-4"] },
	{ name: "Liechtenstein", dial_code: "+423", code: "LI", mask: codes["3-3-3-4"] },
	{ name: "Lithuania", dial_code: "+370", code: "LT", mask: codes["3-3-3-2-2"] },
	{ name: "Luxembourg", dial_code: "+352", code: "LU", mask: codes["3-3-3-3"] },
	{ name: "Macao", dial_code: "+853", code: "MO", mask: codes["3-4-4"] },
	{ name: "Macedonia", dial_code: "+389", code: "MK", mask: codes["3-2-3-3"] },
	{ name: "Madagascar", dial_code: "+261", code: "MG", mask: codes["3-2-2-5"] },
	{ name: "Malawi", dial_code: "+265", code: "MW", mask: codes["3-1-4-4"] },
	{ name: "Malaysia", dial_code: "+60", code: "MY", mask: codes["2-3-3-3"] },
	{ name: "Maldives", dial_code: "+960", code: "MV", mask: codes["3-3-4"] },
	{ name: "Mali", dial_code: "+223", code: "ML", mask: codes["3-2-2-4"] },
	{ name: "Malta", dial_code: "+356", code: "MT", mask: codes["3-4-4"] },
	{ name: "Marshall Islands", dial_code: "+692", code: "MH", mask: codes["3-3-4"] },
	{ name: "Martinique", dial_code: "+596", code: "MQ", mask: codes["3-3-2-2-2"] },
	{ name: "Mauritania", dial_code: "+222", code: "MR", mask: codes["3-2-2-4"] },
	{ name: "Mauritius", dial_code: "+230", code: "MU", mask: codes["3-3-4"] },
	{ name: "Mayotte", dial_code: "+262", code: "YT", mask: codes["3-5-4"] },
	{ name: "Mexico", dial_code: "+52", code: "MX", mask: codes["2-3-3-4"] },
	{ name: "Micronesia, Federated States of Micronesia", dial_code: "+691", code: "FM", mask: codes["3-3-4"] },
	{ name: "Moldova", dial_code: "+373", code: "MD", mask: codes["3-4-4"] },
	{ name: "Monaco", dial_code: "+377", code: "MC", mask: codes["3-3-3-3"] },
	{ name: "Mongolia", dial_code: "+976", code: "MN", mask: codes["3-2-2-4"] },
	{ name: "Montenegro", dial_code: "+382", code: "ME", mask: codes["3-2-3-3"] },
	{ name: "Montserrat", dial_code: "+1664", code: "MS", mask: codes["1-3-3-4"] },
	{ name: "Morocco", dial_code: "+212", code: "MA", mask: codes["3-2-4-3"] },
	{ name: "Mozambique", dial_code: "+258", code: "MZ", mask: codes["3-2-3-3"] },
	{ name: "Myanmar", dial_code: "+95", code: "MM", mask: codes["2-2-3-3"] },
	{ name: "Namibia", dial_code: "+264", code: "NA", mask: codes["3-2-3-4"] },
	{ name: "Nauru", dial_code: "+674", code: "NR", mask: codes["3-3-4"] },
	{ name: "Nepal", dial_code: "+977", code: "NP", mask: codes["3-2-3-3"] },
	{ name: "Netherlands", dial_code: "+31", code: "NL", mask: codes["2-2-3-4"] },
	{ name: "Netherlands Antilles", dial_code: "+599", code: "AN", mask: codes["3-3-4"] },
	{ name: "New Caledonia", dial_code: "+687", code: "NC", mask: codes["3-2-4"] },
	{ name: "New Zealand", dial_code: "+64", code: "NZ", mask: codes["2-3-3-4"] },
	{ name: "Nicaragua", dial_code: "+505", code: "NI", mask: codes["3-4-4"] },
	{ name: "Niger", dial_code: "+227", code: "NE", mask: codes["3-2-2-4"] },
	{ name: "Nigeria", dial_code: "+234", code: "NG", mask: codes["3-3-3-4"] },
	{ name: "Niue", dial_code: "+683", code: "NU", mask: codes["3-4"] },
	{ name: "Norfolk Island", dial_code: "+672", code: "NF", mask: codes["3-3-3"] },
	{ name: "Northern Mariana Islands", dial_code: "+1670", code: "MP", mask: codes["1-3-3-4"] },
	{ name: "Norway", dial_code: "+47", code: "NO", mask: codes["2-3-2-3"] },
	{ name: "Oman", dial_code: "+968", code: "OM", mask: codes["3-2-3-3"] },
	{ name: "Pakistan", dial_code: "+92", code: "PK", mask: codes["2-3-3-4"] },
	{ name: "Palau", dial_code: "+680", code: "PW", mask: codes["3-3-4"] },
	{ name: "Palestinian Territory, Occupied", dial_code: "+970", code: "PS", mask: codes["3-2-3-4"] },
	{ name: "Panama", dial_code: "+507", code: "PA", mask: codes["3-3-4"] },
	{ name: "Papua New Guinea", dial_code: "+675", code: "PG", mask: codes["3-3-2-3"] },
	{ name: "Paraguay", dial_code: "+595", code: "PY", mask: codes["3-3-3-3"] },
	{ name: "Peru", dial_code: "+51", code: "PE", mask: codes["2-3-3-3"] },
	{ name: "Philippines", dial_code: "+63", code: "PH", mask: codes["2-3-3-4"] },
	{ name: "Pitcairn", dial_code: "+64", code: "PN", mask: codes["2-3-3-4"] },
	{ name: "Poland", dial_code: "+48", code: "PL", mask: codes["2-3-3-3"] },
	{ name: "Portugal", dial_code: "+351", code: "PT", mask: codes["3-2-3-4"] },
	{ name: "Puerto Rico", dial_code: "+1939", code: "PR", mask: codes["1-3-3-4"] },
	{ name: "Qatar", dial_code: "+974", code: "QA", mask: codes["3-4-4"] },
	{ name: "Romania", dial_code: "+40", code: "RO", mask: codes["2-2-3-4"] },
	{ name: "Russia", dial_code: "+7", code: "RU", mask: codes["1-3-3-2-2"] },
	{ name: "Rwanda", dial_code: "+250", code: "RW", mask: codes["3-3-3-3"] },
	{ name: "Reunion", dial_code: "+262", code: "RE", mask: codes["3-5-4"] },
	{ name: "Saint Barthelemy", dial_code: "+590", code: "BL", mask: codes["3-3-3-3"] },
	{ name: "Saint Helena, Ascension and Tristan Da Cunha", dial_code: "+290", code: "SH", mask: codes["3-4"] },
	{ name: "Saint Kitts and Nevis", dial_code: "+1869", code: "KN", mask: codes["1-3-3-4"] },
	{ name: "Saint Lucia", dial_code: "+1758", code: "LC", mask: codes["1-3-3-4"] },
	{ name: "Saint Martin", dial_code: "+590", code: "MF", mask: codes["3-3-3-3"] },
	{ name: "Saint Pierre and Miquelon", dial_code: "+508", code: "PM", mask: codes["3-2-4"] },
	{ name: "Saint Vincent and the Grenadines", dial_code: "+1784", code: "VC", mask: codes["1-3-3-4"] },
	{ name: "Samoa", dial_code: "+685", code: "WS", mask: codes["3-2-4"] },
	{ name: "San Marino", dial_code: "+378", code: "SM", mask: codes["3-4-6"] },
	{ name: "Sao Tome and Principe", dial_code: "+239", code: "ST", mask: codes["3-2-5"] },
	{ name: "Saudi Arabia", dial_code: "+966", code: "SA", mask: codes["3-1-4-4"] },
	{ name: "Senegal", dial_code: "+221", code: "SN", mask: codes["3-2-3-4"] },
	{ name: "Serbia", dial_code: "+381", code: "RS", mask: codes["3-2-3-4"] },
	{ name: "Seychelles", dial_code: "+248", code: "SC", mask: codes["3-1-3-3"] },
	{ name: "Sierra Leone", dial_code: "+232", code: "SL", mask: codes["3-2-6"] },
	{ name: "Singapore", dial_code: "+65", code: "SG", mask: codes["2-4-4"] },
	{ name: "Slovakia", dial_code: "+421", code: "SK", mask: codes["3-3-3-3"] },
	{ name: "Slovenia", dial_code: "+386", code: "SI", mask: codes["3-2-3-3"] },
	{ name: "Solomon Islands", dial_code: "+677", code: "SB", mask: codes["3-3-4"] },
	{ name: "Somalia", dial_code: "+252", code: "SO", mask: codes["3-2-3-3"] },
	{ name: "South Africa", dial_code: "+27", code: "ZA", mask: codes["2-2-3-4"] },
	{ name: "South Sudan", dial_code: "+211", code: "SS", mask: codes["3-2-3-4"] },
	{ name: "South Georgia and the South Sandwich Islands", dial_code: "+500", code: "GS", mask: codes["3-5"] },
	{ name: "Spain", dial_code: "+34", code: "ES", mask: codes["2-3-3-3"] },
	{ name: "Sri Lanka", dial_code: "+94", code: "LK", mask: codes["2-2-3-4"] },
	{ name: "Sudan", dial_code: "+249", code: "SD", mask: codes["3-2-3-4"] },
	{ name: "Suriname", dial_code: "+597", code: "SR", mask: codes["3-3-4"] },
	{ name: "Svalbard and Jan Mayen", dial_code: "+47", code: "SJ", mask: codes["2-3-2-3"] },
	{ name: "Swaziland", dial_code: "+268", code: "SZ", mask: codes["3-2-2-4"] },
	{ name: "Sweden", dial_code: "+46", code: "SE", mask: codes["2-2-3-4"] },
	{ name: "Switzerland", dial_code: "+41", code: "CH", mask: codes["2-2-3-4"] },
	{ name: "Syrian Arab Republic", dial_code: "+963", code: "SY", mask: codes["3-2-4-3"] },
	{ name: "Taiwan", dial_code: "+886", code: "TW", mask: codes["3-1-4-4"] },
	{ name: "Tajikistan", dial_code: "+992", code: "TJ", mask: codes["3-2-3-4"] },
	{ name: "Tanzania, United Republic of Tanzania", dial_code: "+255", code: "TZ", mask: codes["3-2-3-4"] },
	{ name: "Thailand", dial_code: "+66", code: "TH", mask: codes["2-2-3-4"] },
	{ name: "Timor-Leste", dial_code: "+670", code: "TL", mask: codes["3-3-5"] },
	{ name: "Togo", dial_code: "+228", code: "TG", mask: codes["3-2-3-3"] },
	{ name: "Tokelau", dial_code: "+690", code: "TK", mask: codes["3-4"] },
	{ name: "Tonga", dial_code: "+676", code: "TO", mask: codes["3-5"] },
	{ name: "Trinidad and Tobago", dial_code: "+1868", code: "TT", mask: codes["1-3-3-4"] },
	{ name: "Tunisia", dial_code: "+216", code: "TN", mask: codes["3-2-3-3"] },
	{ name: "Turkey", dial_code: "+90", code: "TR", mask: codes["2-3-3-4"] },
	{ name: "Turkmenistan", dial_code: "+993", code: "TM", mask: codes["3-1-3-4"] },
	{ name: "Turks and Caicos Islands", dial_code: "+1649", code: "TC", mask: codes["1-3-3-4"] },
	{ name: "Tuvalu", dial_code: "+688", code: "TV", mask: codes["3-6"] },
	{ name: "Uganda", dial_code: "+256", code: "UG", mask: codes["3-3-3-3"] },
	{ name: "Ukraine", dial_code: "+380", code: "UA", mask: codes["3-2-3-2-2"] },
	{ name: "United Arab Emirates", dial_code: "+971", code: "AE", mask: codes["3-2-3-4"] },
	{ name: "United Kingdom", dial_code: "+44", code: "GB", mask: codes["2-2-4-4"] },
	{ name: "United States", dial_code: "+1", code: "US", mask: codes["1-3-3-4"] },
	{ name: "Uruguay", dial_code: "+598", code: "UY", mask: codes["3-1-3-2-2"] },
	{ name: "Uzbekistan", dial_code: "+998", code: "UZ", mask: codes["3-2-3-4"] },
	{ name: "Vanuatu", dial_code: "+678", code: "VU", mask: codes["3-2-5"] },
	{ name: "Venezuela, Bolivarian Republic of Venezuela", dial_code: "+58", code: "VE", mask: codes["2-3-3-4"] },
	{ name: "Vietnam", dial_code: "+84", code: "VN", mask: codes["2-3-4-3"] },
	{ name: "Virgin Islands, British", dial_code: "+1284", code: "VG", mask: codes["1-3-3-4"] },
	{ name: "Virgin Islands, U.S.", dial_code: "+1340", code: "VI", mask: codes["1-3-3-4"] },
	{ name: "Wallis and Futuna", dial_code: "+681", code: "WF", mask: codes["3-2-4"] },
	{ name: "Yemen", dial_code: "+967", code: "YE", mask: codes["3-3-3-3"] },
	{ name: "Zambia", dial_code: "+260", code: "ZM", mask: codes["3-2-3-4"] },
	{ name: "Zimbabwe", dial_code: "+263", code: "ZW", mask: codes["3-1-6"] },
];
